# AUTOGENERATED FROM 'app/queries/meeting/create_meeting.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations

import dataclasses
import uuid
from typing import cast

import edgedb


@dataclasses.dataclass
class CreateMeetingResult:
    id: uuid.UUID
    url_code: str


async def create_meeting(
    executor: edgedb.AsyncIOExecutor,
    *,
    url_code: str,
) -> CreateMeetingResult:
    return cast(
        CreateMeetingResult,
        await executor.query_single(
            """\
        WITH
            url_code := <str>$url_code
        SELECT (
            INSERT Meeting {
                url_code := url_code,
            }
        ) {url_code}\
        """,
            url_code=url_code,
        ),
    )
