name: CI

on:
  push:

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the codes
        uses: actions/checkout@v4

      - name: Cache Poetry binary
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.poetry
          key: poetry-2.3.2

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=$HOME/.poetry python3 - --version 2.3.2

      - name: Register Poetry bin
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run Black
        run: poetry run black . --check

      - name: Run Ruff
        run: |
          poetry run ruff check --select I
          poetry run ruff check

      - name: Run Mypy
        run: poetry run mypy .

  test:
    runs-on: ubuntu-22.04
    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 11123
      MYSQL_DATABASE: fastapi_study

    steps:
      - name: Check out the codes
        uses: actions/checkout@v4

      - name: Cache Poetry binary
        id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.poetry
          key: poetry-2.3.2

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=$HOME/.poetry python3 - --version 2.3.2

      - name: Register Poetry bin
        run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-root

      - name: Setup edgedb
        uses: edgedb/setup-edgedb@v1

      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime

      - name: Start Mysql
        run: |
          sudo systemctl start mysql
          mysql -e "use mysql; FLUSH PRIVILEGES; ALTER USER '${{ env.MYSQL_USER }}'@'localhost' IDENTIFIED BY '${{ env.MYSQL_PASSWORD }}';" -uroot -proot
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}
          

      - name: Run tests
        run: |
          poetry run coverage run -m pytest .
          poetry run coverage report -m